#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

fn-git-rev-pre-receive-app() {
  # shellcheck disable=SC2034
  declare APP="$1" IMAGE_SOURCE_TYPE="$2" TMP_WORK_DIR="$3" REV="$4"

  # Don't write the revision if there is no git repository or we have no incoming REV.
  if [[ -d "$DOKKU_ROOT/$APP/refs" ]] && [[ -n "$REV" ]]; then
    dokku_log_info1 "Setting git environment variables..."
    config_set --no-restart "$APP" GIT_REV="$REV"
    config_set --no-restart "$APP" GIT_VERSION="$(GIT_DIR=$DOKKU_ROOT/$APP git describe --tags --always)"
    config_set --no-restart "$APP" GIT_COMMITDATE="$(GIT_DIR=$DOKKU_ROOT/$APP git log -1 --format=%cd)"
  fi
}

fn-git-rev-pre-receive-app "$@"
