#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$PLUGIN_AVAILABLE_PATH/config/functions"

main() {
  declare APP="$1"

  # Don't write the revision if there is no git repository.
  if [[ -d "$DOKKU_ROOT/$APP/refs" ]]; then
    dokku_log_info1 "Setting git environment variables..."
    config_set --no-restart "$APP" GIT_REV="$(GIT_DIR=$DOKKU_ROOT/$APP git log -1 --format=%H)"
    config_set --no-restart "$APP" GIT_VERSION="$(GIT_DIR=$DOKKU_ROOT/$APP git describe --tags --always)"
    config_set --no-restart "$APP" GIT_COMMITDATE="$(GIT_DIR=$DOKKU_ROOT/$APP git log -1 --format=%cd)"
  fi
}

main "$@"
